from django.db import models
from django.contrib.auth.models import AbstractUser
from operator import itemgetter

TMDB_LOCALES = [
( "BO", "Bolivia"),
( "BH", "Bahrain"),
( "CD", "Congo"),
( "CO", "Colombia"),
( "EE", "Estonia"),
( "ES", "Spain"),
( "FR", "France"),
( "KN", "St. Kitts and Nevis"),
( "MA", "Morocco"),
( "MH", "Marshall Islands"),
( "MQ", "Martinique"),
( "MX", "Mexico"),
( "RO", "Romania"),
( "ZA", "South Africa"),
( "CG", "Congo"),
( "CZ", "Czech Republic"),
( "DZ", "Algeria"),
( "GS", "South Georgia and the South Sandwich Islands"),
( "HM", "Heard and McDonald Islands"),
( "ID", "Indonesia"),
( "IQ", "Iraq"),
( "ML", "Mali"),
( "NC", "New Caledonia"),
( "YU", "Yugoslavia"),
( "RW", "Rwanda"),
( "SG", "Singapore"),
( "SK", "Slovakia"),
( "SR", "Suriname"),
( "TH", "Thailand"),
( "TM", "Turkmenistan"),
( "UM", "United States Minor Outlying Islands"),
( "SS", "South Sudan"),
( "AD", "Andorra"),
( "AE", "United Arab Emirates"),
( "BF", "Burkina Faso"),
( "CR", "Costa Rica"),
( "EC", "Ecuador"),
( "FJ", "Fiji"),
( "GI", "Gibraltar"),
( "KM", "Comoros"),
( "LC", "St. Lucia"),
( "NZ", "New Zealand"),
( "XK", "Kosovo"),
( "SB", "Solomon Islands"),
( "TC", "Turks and Caicos Islands"),
( "UY", "Uruguay"),
( "VC", "St. Vincent and the Grenadines"),
( "YE", "Yemen"),
( "CF", "Central African Republic"),
( "AT", "Austria"),
( "AN", "Netherlands Antilles"),
( "BZ", "Belize"),
( "CX", "Christmas Island"),
( "ET", "Ethiopia"),
( "GF", "French Guiana"),
( "GM", "Gambia"),
( "GU", "Guam"),
( "KH", "Cambodia"),
( "LB", "Lebanon"),
( "PG", "Papua New Guinea"),
( "PY", "Paraguay"),
( "VA", "Holy See"),
( "BS", "Bahamas"),
( "DM", "Dominica"),
( "GE", "Georgia"),
( "GP", "Guadaloupe"),
( "GT", "Guatemala"),
( "GW", "Guinea-Bissau"),
( "HU", "Hungary"),
( "IT", "Italy"),
( "KP", "North Korea"),
( "LR", "Liberia"),
( "LT", "Lithuania"),
( "MC", "Monaco"),
( "MK", "Macedonia"),
( "XC", "Czechoslovakia"),
( "SC", "Seychelles"),
( "SN", "Senegal"),
( "VG", "British Virgin Islands"),
( "AO", "Angola"),
( "BY", "Belarus"),
( "CI", "Cote D'Ivoire"),
( "CM", "Cameroon"),
( "CN", "China"),
( "EG", "Egypt"),
( "ER", "Eritrea"),
( "JM", "Jamaica"),
( "KE", "Kenya"),
( "MN", "Mongolia"),
( "MU", "Mauritius"),
( "NA", "Namibia"),
( "QA", "Qatar"),
( "RU", "Russia"),
( "TZ", "Tanzania"),
( "BA", "Bosnia and Herzegovina"),
( "AG", "Antigua and Barbuda"),
( "BM", "Bermuda"),
( "DJ", "Djibouti"),
( "IE", "Ireland"),
( "MV", "Maldives"),
( "MY", "Malaysia"),
( "MZ", "Mozambique"),
( "NO", "Norway"),
( "SE", "Sweden"),
( "SM", "San Marino"),
( "SO", "Somalia"),
( "TN", "Tunisia"),
( "XG", "East Germany"),
( "AF", "Afghanistan"),
( "CS", "Serbia and Montenegro"),
( "KY", "Cayman Islands"),
( "KZ", "Kazakhstan"),
( "LK", "Sri Lanka"),
( "MM", "Myanmar"),
( "MS", "Montserrat"),
( "WS", "Samoa"),
( "SU", "Soviet Union"),
( "BD", "Bangladesh"),
( "AQ", "Antarctica"),
( "AM", "Armenia"),
( "AI", "Anguilla"),
( "BB", "Barbados"),
( "BT", "Bhutan"),
( "CL", "Chile"),
( "FK", "Falkland Islands"),
( "GN", "Guinea"),
( "GY", "Guyana"),
( "HT", "Haiti"),
( "IR", "Iran"),
( "JP", "Japan"),
( "PS", "Palestinian Territory"),
( "SA", "Saudi Arabia"),
( "SD", "Sudan"),
( "SH", "St. Helena"),
( "TR", "Turkey"),
( "TW", "Taiwan"),
( "VI", "US Virgin Islands"),
( "VU", "Vanuatu"),
( "ZM", "Zambia"),
( "AU", "Australia"),
( "BN", "Brunei Darussalam"),
( "BV", "Bouvet Island"),
( "DE", "Germany"),
( "HR", "Croatia"),
( "LV", "Latvia"),
( "LY", "Libyan Arab Jamahiriya"),
( "NU", "Niue"),
( "SJ", "Svalbard & Jan Mayen Islands"),
( "SV", "El Salvador"),
( "TD", "Chad"),
( "UG", "Uganda"),
( "BJ", "Benin"),
( "CA", "Canada"),
( "CV", "Cape Verde"),
( "DO", "Dominican Republic"),
( "RS", "Serbia"),
( "IS", "Iceland"),
( "KG", "Kyrgyz Republic"),
( "LS", "Lesotho"),
( "MG", "Madagascar"),
( "NI", "Nicaragua"),
( "PK", "Pakistan"),
( "PT", "Portugal"),
( "TF", "French Southern Territories"),
( "TO", "Tonga"),
( "ZW", "Zimbabwe"),
( "AW", "Aruba"),
( "BR", "Brazil"),
( "DK", "Denmark"),
( "GB", "United Kingdom"),
( "GR", "Greece"),
( "MW", "Malawi"),
( "NL", "Netherlands"),
( "TG", "Togo"),
( "TJ", "Tajikistan"),
( "TL", "Timor-Leste"),
( "TT", "Trinidad and Tobago"),
( "UZ", "Uzbekistan"),
( "VE", "Venezuela"),
( "YT", "Mayotte"),
( "AZ", "Azerbaijan"),
( "CH", "Switzerland"),
( "CK", "Cook Islands"),
( "FM", "Micronesia"),
( "GD", "Grenada"),
( "HN", "Honduras"),
( "IO", "British Indian Ocean Territory"),
( "MD", "Moldova"),
( "MP", "Northern Mariana Islands"),
( "NP", "Nepal"),
( "PL", "Poland"),
( "PN", "Pitcairn Island"),
( "PR", "Puerto Rico"),
( "SL", "Sierra Leone"),
( "ST", "Sao Tome and Principe"),
( "SY", "Syrian Arab Republic"),
( "TK", "Tokelau"),
( "TV", "Tuvalu"),
( "UA", "Ukraine"),
( "AR", "Argentina"),
( "BI", "Burundi"),
( "BW", "Botswana"),
( "CY", "Cyprus"),
( "FI", "Finland"),
( "GL", "Greenland"),
( "IN", "India"),
( "KW", "Kuwait"),
( "LI", "Liechtenstein"),
( "MO", "Macao"),
( "MT", "Malta"),
( "NE", "Niger"),
( "ME", "Montenegro"),
( "NR", "Nauru"),
( "OM", "Oman"),
( "PE", "Peru"),
( "SI", "Slovenia"),
( "VN", "Vietnam"),
( "AL", "Albania"),
( "AS", "American Samoa"),
( "BE", "Belgium"),
( "CC", "Cocos  Islands"),
( "CU", "Cuba"),
( "GA", "Gabon"),
( "GH", "Ghana"),
( "JO", "Jordan"),
( "KI", "Kiribati"),
( "LA", "Lao People's Democratic Republic"),
( "LU", "Luxembourg"),
( "MR", "Mauritania"),
( "NF", "Norfolk Island"),
( "PA", "Panama"),
( "PF", "French Polynesia"),
( "PH", "Philippines"),
( "PM", "St. Pierre and Miquelon"),
( "PW", "Palau"),
( "RE", "Reunion"),
( "US", "United States of America"),
( "WF", "Wallis and Futuna Islands"),
( "BG", "Bulgaria"),
( "EH", "Western Sahara"),
( "FO", "Faeroe Islands"),
( "GQ", "Equatorial Guinea"),
( "HK", "Hong Kong"),
( "IL", "Israel"),
( "NG", "Nigeria"),
( "SZ", "Swaziland"),
( "KR", "South Korea"),
]
MEDIA_TYPES = [
    ('tv', 'TV'),
    ('movie', 'MOVIE'),
]
# Create your models here.
class User(AbstractUser):
    api_key = models.CharField(
                        max_length=50
                        )
    profile_img = models.CharField(
                        max_length=50,
                        blank=True,
                        )
    locale = models.CharField(
                        max_length=2,
                        default='US',
                        choices=sorted(TMDB_LOCALES, key=itemgetter(1)),
                        )

class Favorite(models.Model):
    owner = models.ForeignKey(
                        User,
                        related_name='favorite_item',
                        on_delete=models.CASCADE,
                        ) 
    media_type = models.CharField(
                        max_length = 5,
                        default = 'movie',
                        choices = MEDIA_TYPES,
                        )
    media_id = models.CharField(
                        max_length = 30,
                        )

class WatchList(models.Model):
    owner = models.ForeignKey(
                        User,
                        related_name='watchlist_item',
                        on_delete=models.CASCADE
    )
    media_type = models.CharField(
                        max_length = 5,
                        default = 'movie',
                        choices = MEDIA_TYPES,
                        )
    media_id = models.CharField(
                        max_length = 30,
                        )
