# Generated by Django 3.1.2 on 2020-12-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20201201_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='14ca02e9e44c14f256a20cfed90c4149', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
