# Generated by Django 3.1.2 on 2020-12-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20201205_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='films/'),
        ),
    ]
