# Generated by Django 3.1.2 on 2020-12-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('US', 'United States')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
